
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PHR Serverless API (staging)

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Runtime: python3.11
    Architectures:
      - x86_64
    Environment:
      Variables:
        STAGE: staging

Resources:
  PhrTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: phr-staging
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  PhrApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      Auth:
        Authorizers:
          CognitoAuthorizer:
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPoolId}"
              audience:
                - !Ref CognitoAppClientId
            IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: CognitoAuthorizer

  PhrFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PhrTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PhrTable
      Events:
        ProxyApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref PhrApi
            Path: /{proxy+}
            Method: ANY

Parameters:
  CognitoUserPoolId:
    Type: String
    Description: Cognito User Pool ID (e.g., us-east-2_abc123)
  CognitoAppClientId:
    Type: String
    Description: Cognito App Client ID (SPA/public client; no secret)

Outputs:
  ApiUrl:
    Description: API Gateway endpoint
    Value: !Sub "https://${PhrApi}.execute-api.${AWS::Region}.amazonaws.com"

